name: EAS Build Android Play Store

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: EAS Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with EAS
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas login --token $EAS_TOKEN

      - name: Trigger Android Build
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build --platform android --profile production
